### ISSUE TITLE
Can you fix sukebei nyaa?

### ISSUE THREAD

**Issue by Pireo** [kenken28/NyaaPantsu-qBittorrent-Plugin#1]
https://raw.githubusercontent.com/4chenz/pantsu-plugin/master/sukebei.py

Your nyaa pantsu plugin works perfectly, I think we should remove the other one because it has issues (doesn't redirect to page etc...) and you may fix the sukebei too.

**Comment by kenken28** [comment]
Sure thing. I've been pretty busy recently, please give me a few days. I
will take a look at it within this week.

2017年9月18日(月) 5:08 Pireo <notifications@github.com>:

**Comment by kenken28** [comment]
Well, turned out that I'm too lazy to fix 4chanz's code, I took 1 minute making a tiny change to my NyaaPantsu plugin and turned it into a SukebeiPantsu plugin. Here's my lazy solution - [sukebeipantsu.py](https://github.com/kenken28/NyaaPantsu-qBittorrent-Plugin/blob/master/sukebeipantsu.py)

**Comment by Pireo** [comment]
Thanks for it. The problem is, 4chanz plugin doesn't redirect to the web page. Anyway, when you have time, I'm interested in these:
http://tparser.org/ (no ads, good stuff not found elsewhere)
http://7tor.download/Movies/Browse.aspx (there was yts as a movie-based site before but now it's fake and this seems better)
http://www.mejortorrent.com/ (the most popular spanish torrent site http://torrentnote.com/spanish-torrent-sites) if you do this, I'll delete divxtotal which doesn't work.

**Comment by kenken28** [comment]
I can’t promise, but I’ll have a look when I have the time to.

2017年9月19日(火) 2:23 Pireo <notifications@github.com>:
